#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  scripts/bundle_docs.sh [--output <path>] [--root <repo_root>]

Creates a single Markdown document by concatenating all *.md files in the repo
in a deterministic order (a curated "front matter" set first, then everything
else sorted by path).

Defaults:
  --output dist/lumen-docs.md
EOF
}

output="dist/lumen-docs.md"
repo_root=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --output)
      output="${2:-}"
      shift 2
      ;;
    --root)
      repo_root="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "error: unknown arg: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ -z "$repo_root" ]]; then
  if repo_root="$(git rev-parse --show-toplevel 2>/dev/null)"; then
    :
  else
    repo_root="$(pwd)"
  fi
fi

cd "$repo_root"

mkdir -p "$(dirname "$output")"

tmp="$(mktemp)"
docs_list="$(mktemp)"
trap 'rm -f "$tmp" "$docs_list"' EXIT

# Prefer a stable, human-friendly ordering for the main docs, then add everything else.
preferred=(
  "README.md"
  "PITCH.md"
  "DESIGN_RATIONALE.md"
  "SPEC.md"
  "LUMEN_EBNF.md"
  "FFI_ABI.md"
  "CORELIB.md"
  "TOOLING.md"
  "CLI.md"
  "COMPATIBILITY.md"
  "ERRORS.md"
  "COMPILER_MVP.md"
  "ROADMAP.md"
)

{
  for f in "${preferred[@]}"; do
    [[ -f "$f" ]] && echo "$f"
  done

  find . \
    -type f \
    -name '*.md' \
    -not -path './.git/*' \
    -not -path './dist/*' \
    -print \
    | sed 's|^\./||' \
    | LC_ALL=C sort
} | awk '!seen[$0]++' >"$docs_list"

docs=()
while IFS= read -r f; do
  docs+=("$f")
done <"$docs_list"

{
  echo "# Lumen — Documentation Bundle"
  echo
  echo "> Generated by \`scripts/bundle_docs.sh\` on $(date -u '+%Y-%m-%d %H:%M:%SZ')"
  echo
  echo "## Included files"
  for f in "${docs[@]}"; do
    echo "- \`$f\`"
  done
  echo
} >"$tmp"

for f in "${docs[@]}"; do
  {
    echo
    echo "---"
    echo
    echo "## File: \`$f\`"
    echo
    cat "$f"
    echo
  } >>"$tmp"
done

mv "$tmp" "$output"
trap - EXIT

echo "Wrote $output"
